# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.cache/wt [current_project]
set_property parent.project_path C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/or_gate2.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/MUX312.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/and_gate2.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/full_adder2.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/ALU4.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/Signextend1.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/mux2_11.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/Registers2.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/ALU_16Bit3.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/Control1.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/PC_REG.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/mux3_11.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/Memory.vhd
  C:/Users/asehra/Group14_FinalProject_Part1/Group14_FinalProject_Part1.srcs/sources_1/imports/Downloads/CPU_33802.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CPU_3380 -part xc7a100tcsg324-2


write_checkpoint -force -noxdef CPU_3380.dcp

catch { report_utilization -file CPU_3380_utilization_synth.rpt -pb CPU_3380_utilization_synth.pb }
